### ISSUE TITLE
Change Forms Bar (UX Improvement + UI Inconsistency)

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#232]
After having tested the form this bar at the top is not easy to use. A list of UX limitation
•	Submit button should be at the bottom ( I need to submit when I am at the bottom of the page, the SUBMIT action should in the workflow/UX when I need it)
•	Add a next button below the page after every section to avoid continuously scrolling up (Initiative Form).
•	Hard to distinguish between error and required fields (In case of an error, highlight only the field with the error instead of all the required fields. It looks like all the fields have an error.)
•	Required fields looks a bit obsolete since from a user standpoint all I want to know is whether I can submit or not. So required fields should only show if I have not filled those out when I click “Next” or “Submit”
•	There should be an error message if one inputs future dates for both FIRST PUBLICATION DATE and LAST AMENDMENT DATE. There should be an error message if the first publication date is a date that comes after the last amendment date.

![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/ce435ff8-cd71-496a-98ae-366f94eee3a2)
![image.png](https://images.zenhubusercontent.com/605b1d5f0fab1a20720e41e1/44a8d3e6-778c-48a8-a66d-b79ec292788f)

**Comment by loicsans** [comment]
https://xd.adobe.com/view/e0f0b416-7cec-4162-b529-de5e54540adb-b5a3/
Here are improvement on required vs error messages

**Comment by loicsans** [comment]
When triggering the "Required fields highlighted" and to avoid the flickering when the border truns green, we should start with a transparent border by default (border: 2px solid transparent;) on each inputs
[Uploading... Screenshot 2021-05-21 at 15.32.47.png]

**Comment by dedenbangkit** [comment]
Flickering on switch required issue is fixed

**Comment by martaotto** [comment]
@loicsans 

these changes are still needed:
 "Add a next button below the page after every section to avoid continuously scrolling up (Initiative Form)."

I think a next button at at the bottom is still needed. I am still not convinced of the SUBMIT button at the top since that should only show once they have completed the full form it can actually be submitted.

**Comment by loicsans** [comment]
As I mentioned in a comment earlier: https://xd.adobe.com/view/9ce49c94-9181-4429-a015-fa433959f557-c9b7/
On the initiative form and any other form that will require an extra navigation, the left handside bar serves as an indicator and should be anchored when scrolling, that way the user always knows where he is and what's the next step

**Comment by iperdomo** [comment]
> On the initiative form and any other form that will require an extra navigation, the left handside bar serves as an indicator and should be anchored when scrolling, that way the user always knows where he is and what's the next step

IMHO, I don't think is *evident* that you need to go to the left and click the next section to move forward, e.g. I filled the first question, everything is *green*. What do I do next? I know now that I need to *click* the next section to move forward, but is this *intuitive* enough ? 🤔 
![2021-05-28_1660x879](https://user-images.githubusercontent.com/178474/119973948-6259c180-bfb4-11eb-99fa-668b30f6c00f.png)

**Comment by loicsans** [comment]
If It was implemented as designed the next button would be redudant, this was not implemented as intended by the proposed original and approved solution. The main problem is the scrolling back up to go to the next section, not that the user doesn't know what to do next. And even if we end up adding a next button, the user should still be able to see where they are and get and immediate overview of how far they are of completing the task.
